version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 5.0
    build:
        commands:
            - dotnet build -c Release ./RedditApi/RedditApi.csproj
    post_build:
        commands:
            - dotnet publish -c Release

    artifacts:
        files:
            - '**/*'
        base-directory: ./bin/Release/net5.0/publish/